name: 'Aggregate Junit Result'
description: 'Aggregate Junit Result for personal use'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  report_path:
    description: 'Junit Report Path'
    required: true
    default: 'build/junit-test/TEST-*.xml'

# Define your outputs here.
outputs:
  totalCount:
    description: 'Total Test Count'
  passed:
    description: 'passed Test Count'
  failed:
    description: 'failed Test Count'
  skipped:
    description: 'skipped Test Count'

runs:
  using: node20
  main: dist/index.js
